### ISSUE TITLE
Basic theory about geostatistical delta-GLMM

### ISSUE THREAD

**Issue by JintaoSHOU** [nwfsc-assess/geostatistical_delta-GLMM#14]
Hi, James can you introduce some basic readings about geostatistical delta-GLMM, I am a newer, your paper, it is more difficult for me. Thanks

**Comment by James-Thorson** [comment]
Have you read the papers listed at the bottom of the GitHub mainpage?  The Thorson et al. ICESJMS 2015 or Shelton et al. CJFAS 2014 is a good start

**Comment by JintaoSHOU** [comment]
Thanks a lot

**Comment by James-Thorson** [comment]
please look over the "Posts" section at www.FishStats.org for more introductory material

**Comment by JintaoSHOU** [comment]
Thanks again
