### ISSUE TITLE
Geostat_Sim ObsModel

### ISSUE THREAD

**Issue by kellijohnson** [nwfsc-assess/geostatistical_delta-GLMM#16]
`Geostat_Sim()` only works if you have `ObsModel` in your global environment and if `length(ObsModel) = 2`, which is not true for some of the examples in the repository. The inclusion of `ObsModel` was done in c66bb96. I know how to fix the issue, I am just not sure if you want to change it from its current length of two to one because only the second element is used and what you (@James-Thorson) want the default value to be, which I am guessing should be two for the second element based on some of the example code?

**Comment by kellijohnson** [comment]
I found another potential bug. Should the variance in your internal function [`RFsim`](https://github.com/nwfsc-assess/geostatistical_delta-GLMM/blob/master/R/Geostat_Sim.R#L34) be specific to the model that you are using and not set to the object in the function called `model_O1`? Also, I am unsure of the math here, but wouldn't you want to divide by the product of the standard deviations rather than divide by the standard deviation of the data and then multiply by the standard deviation of the model?

**Comment by James-Thorson** [comment]
Thanks for catching two bugs:

1.  ObsModel default now at c(0,2)
2.  RFsim now uses `model` not `model_O1`

I'm not bothering with the length of ObsModel, and the standard deviation calculation is correct as is (its turned off by default anyway, and is correctly ensuring that the sample standard deviation is equal to the input population-SD)
