### ISSUE TITLE
error in SpatialDeltaGLMM_example with function PlotIndex_Fn

### ISSUE THREAD

**Issue by areeder8** [nwfsc-assess/geostatistical_delta-GLMM#22]
I'm trying to run through the example script and this line:
Index = PlotIndex_Fn( DirName=DateFile, 
                      TmbData=TmbData, 
                      Sdreport=Opt[["SD"]], 
                      Year_Set=Year_Set, 
                      Years2Include=Years2Include, 
                      strata_names=strata.limits[,1], 
                      use_biascorr=TRUE )

gives this error:
Error in TmbData$t_i[, 1] : incorrect number of dimensions

I'm not sure what i can do to fix this error. 
Thanks!

**Comment by James-Thorson** [comment]
Are you willing to retry using package VAST? SpatialDeltaGLMM is basically
deprecated and VAST can do everything it did plus more.

**Comment by areeder8** [comment]
Yes that is no problem. Looking through the VAST example I see
Index = SpatialDeltaGLMM::PlotIndex_Fn( DirName=DateFile, TmbData=TmbData, Sdreport=Opt[["SD"]], Year_Set=Year_Set, Years2Include=Years2Include, use_biascorr=TRUE )
would that be the code I would use?

**Comment by areeder8** [comment]
I have used that code and it seems to be working!
