### ISSUE TITLE
Spatial grids for the Atlantic and the U.S. Gulf of Mexico

### ISSUE THREAD

**Issue by agruss2** [nwfsc-assess/geostatistical_delta-GLMM#24]
@James-Thorson I am currently working on a six-month project about CPUE standardization for the SEFSC. I am now going to work with VAST. To be able to use VAST, I produced a 1°x1° spatial grid for the northwestern Atlantic and estimated the surface area of each of the cells of that spatial grid (see the .csv file attached here - stored in a zip file).
I am also attaching here the 0.18°x0.18° spatial grid for the U.S. Gulf of Mexico.
Maybe it would be useful to integrate the spatial grids attached here into FishStats or elsewhere, so that they can be reused in future projects? 
Many thanks!
[Lattice_Atlantic_CPUE_project.zip](https://github.com/nwfsc-assess/geostatistical_delta-GLMM/files/1382996/Lattice_Atlantic_CPUE_project.zip)
[Lattice_US_GOM_FLRACEP_project_V2.zip](https://github.com/nwfsc-assess/geostatistical_delta-GLMM/files/1382997/Lattice_US_GOM_FLRACEP_project_V2.zip)

**Comment by James-Thorson** [comment]
I just added a new feature to easily specify a user-supplied extrapolation grid:

```R
Extrapolation_List = Prepare_Extrapolation_Data_Fn( Region="User", strata.limits=strata.limits, input_grid=InputGrid )
```

where `InputGrid` is the values from one of those CSV file.  

I think the Gulf of Mexico grid is already available in package SpatialDeltaGLMM, I'll also add that Atlantic grid if requested by at least one other person.
