### ISSUE TITLE
Updating the "gulf_of_mexico_grid.rda" file provided in this GitHub repository

### ISSUE THREAD

**Issue by agruss2** [nwfsc-assess/geostatistical_delta-GLMM#28]
@James-Thorson 
I recently improved the surface area estimates for the "gulf_of_mexico_grid" I shared with you last year. The new surface area estimates I generated (see [Lattice_US_GOM_FLRACEP_project_V2.zip](https://github.com/nwfsc-assess/geostatistical_delta-GLMM/files/1546533/Lattice_US_GOM_FLRACEP_project_V2.zip)) takes into account the fact that the U.S. Gulf of Mexico spans 8 UTM zones (14Q, 14R, 15Q, 15R, 16Q, 16R, 17Q, 17R),
Could you please update the "gulf_of_mexico_grid.rda" file provided in this GitHub repository? 
Thanks a lot!

**Comment by James-Thorson** [comment]
How different are these new areas?  I don't really have time to update these region-specific grids, could you either try to do it yourself (by making a branch and replacing the `.rda` file in directory `data`), or we could try to work out how to get the user-supplied grid working for the North Atlantic and you could use the new GoM grid that way?

I'm of course happy to do this if it seems like other people are using it too, but hope to avoid changes that only impact a single person and which have a work-around already.
