### ISSUE TITLE
How to get estimated relative abundance 

### ISSUE THREAD

**Issue by JintaoSHOU** [nwfsc-assess/geostatistical_delta-GLMM#29]
Hi, all

Can i use this r package to get the estimated relative abundance?
the equation as follows:
![image](https://user-images.githubusercontent.com/23226847/34460123-dbbb5122-ee40-11e7-913c-6580520b1be8.png)

**Comment by James-Thorson** [comment]
I recommend you switch to using package VAST, which does the same tasks.  Have you worked through the tutorial at:

https://github.com/James-Thorson/VAST/blob/master/examples/VAST--single-species_example.Rmd

...?  It has a section labeled "Index of abundance", and the relative index of abundance can be calculated from that.
