### ISSUE TITLE
Spatial Resolution

### ISSUE THREAD

**Issue by kvert-pre** [nwfsc-assess/geostatistical_delta-GLMM#33]
Would there be a straight forward way to calculate the resolution using mesh knowing that resolution is changing in each triangle. A weighted average ?

**Comment by James-Thorson** [comment]
Yeah, the "average" resolution is the total area in the Extrapolation_grid divided by the number of knots.

If you want a uniform placement of knots, you can do this a few ways but the easiest is to switch to using a 2D AR1 grid:

```R
Method = c("Grid", "Mesh", "Spherical_mesh")[1]
grid_size_km = 100
```

And then play with the value of `grid_size_km` until the 2D AR1 grid has about as many grid cells as the number of knots that you'd like to be using.
