### ISSUE TITLE
multispecies VAST

### ISSUE THREAD

**Issue by EllenY** [nwfsc-assess/geostatistical_delta-GLMM#34]
I am running VAST with 1000 knots for 11 species in RStudio. How can I speed up the Optimize process for estimating the final model?

#5.2 Estimate fixed effect and predict random variables
Opt = TMBhelper::Optimize( obj=Obj, lower=TmbList[["Lower"]], 
  upper=TmbList[["Upper"]], getsd=TRUE, savedir=DateFile, 
  bias.correct=FALSE )

**Comment by James-Thorson** [comment]
Easiest fix:  Install and use Revolution R, which will speed up by factor approx. equal to number of processors on machine.

Other fixes:
* Decrease number of knots
* Decrease number of species
* Decrease number of years
* Decrease / change number of factors, e.g., to start with 1 factor for each component and increase slowly until new factors explain small proportion of total variance, as I did in Thorson et al. 2016 Global Ecology and Biogeography
* Use bigger machine
* Use amazon cloud computer
