### ISSUE TITLE
minor: default setting for `flip_around_dateline` 

### ISSUE THREAD

**Issue by zeroyin** [nwfsc-assess/geostatistical_delta-GLMM#36]
`flip_around_dateline` is defaulted to TRUE here:
https://github.com/nwfsc-assess/geostatistical_delta-GLMM/blob/f653b61f41e49514a63a81445807c9dd946ebae4/R/Prepare_User_Extrapolation_Data_Fn.R#L28

Would it be better to move here so that the user can override it?
https://github.com/nwfsc-assess/geostatistical_delta-GLMM/blob/f653b61f41e49514a63a81445807c9dd946ebae4/R/Prepare_User_Extrapolation_Data_Fn.R#L3

**Comment by James-Thorson** [comment]
Done, thanks
