### ISSUE TITLE
QQ_Fn for multi-species

### ISSUE THREAD

**Issue by zeroyin** [nwfsc-assess/geostatistical_delta-GLMM#37]
https://github.com/nwfsc-assess/geostatistical_delta-GLMM/blob/ef2a8f96c5a84628c603865102bc0536e0753e2e/R/QQ_Fn.R#L3

This function seems not compatible with multi-species result from VAST where `TmbDdata$ObsModel_ez` is used instead of `TmbDdata$ObsModel` (it is also confusing because R recognizes part of a variable name). My suggested possible solutions: 1) open a new function in VAST package; 2) modify the function here and add an argument `which_c` to specify which category to plot, default to 1 for single species. For multi-species, when `which_c = ic`, use `ObsModel = ObsModel_ez[ic, ]`.

**Comment by zeroyin** [comment]
Just noticed that in the early versions of VAST (<3_0_0), you used `"ObsModel"=ObsModel_ez[1,]`; was the update meant to allow for different distributions for different categories.

**Comment by James-Thorson** [comment]
Correct. Please feel free to do a pull request complete with code example illustrating what your concern is and how it's fixed. I doubt I'll have time to take a look in detail otherwise

**Comment by James-Thorson** [comment]
One more thought:  I'm currently working with Arnaud Gruss on a paper demonstrating this feature. Please do be in touch if you're also interested in exploring the idea of fitting multiple heterogenous data types.

**Comment by James-Thorson** [comment]
I think this is working as you'd like now, thanks for contributing code in support of your request!

**Comment by agruss2** [comment]
It seems that some of the changes in the code made to address the present issue have led to new issues. 
Today, I ran the code for the Gulf of Mexico, which is based on the code for the single-species example and got an error message when reaching this bit of the code:
```R
Q = SpatialDeltaGLMM::QQ_Fn( TmbData=TmbData, Report=Report, FileName_PP=paste0(DateFile,"Posterior_Predictive.jpg"), FileName_Phist=paste0(DateFile,"Posterior_Predictive-Histogram.jpg"), FileName_QQ=paste0(DateFile,"Q-Q_plot.jpg"), FileName_Qhist=paste0(DateFile,"Q-Q_hist.jpg"))
```
The error message said that it was not possible to save the jpeg's. (Sorry, I forgot to save the error message). 
To circumvent this problem, I simply set the file names to NULL:
```R
Q = SpatialDeltaGLMM::QQ_Fn( TmbData=TmbData, Report=Report, FileName_PP=NULL, FileName_Phist=NULL, FileName_QQ=NULL, FileName_Qhist=NULL) 
```
And I was then able to have the code run until the end.
I suspect that the changes that are needed in the "QQ_Fn" function are minimal. I will likely try to understand what is going on later roday or tomorrow, but thought I would notify this to you guys earlier in case you have time to solve this issue now. 
Thanks a lot!

**Comment by zeroyin** [comment]
Hi Arnaud,

Thank you for the email. Yes I changed the arguments of the function. The filenames are default and if you want to specify filenames  could you try for example FileName_QQ=File1 without path or extension?

Yihao

On Apr 15, 2018, at 15:15, Arnaud Grüss <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems that some of the changes in the code made to address the present issue have led to new issues.
Today, I ran the code for the Gulf of Mexico, which is based on the code for the single-species example and got an error message when reaching this bit of the code:

Q = SpatialDeltaGLMM::QQ_Fn( TmbData=TmbData, Report=Report, FileName_PP=paste0(DateFile,"Posterior_Predictive.jpg"), FileName_Phist=paste0(DateFile,"Posterior_Predictive-Histogram.jpg"), FileName_QQ=paste0(DateFile,"Q-Q_plot.jpg"), FileName_Qhist=paste0(DateFile,"Q-Q_hist.jpg"))

The error message said that it was not possible to save the jpeg's. (Sorry, I forgot to save the error message).
To circumvent this problem, I simply set the file names to NULL:

Q = SpatialDeltaGLMM::QQ_Fn( TmbData=TmbData, Report=Report, FileName_PP=NULL, FileName_Phist=NULL, FileName_QQ=NULL, FileName_Qhist=NULL)

And I was then able to have the code run until the end.
I suspect that the changes that are needed in the "QQ_Fn" function are minimal. I will likely try to understand what is going on later roday or tomorrow, but thought I would notify this to you guys earlier in case you have time to solve this issue now.
Thanks a lot!
