### ISSUE TITLE
minor: object type of t_i

### ISSUE THREAD

**Issue by zeroyin** [nwfsc-assess/geostatistical_delta-GLMM#40]
https://github.com/nwfsc-assess/geostatistical_delta-GLMM/blob/ef2a8f96c5a84628c603865102bc0536e0753e2e/R/PlotIndex_Fn.R#L127

The example Rmd stopped at this line with an error: `Error in TmbData$t_i[, 1] : incorrect number of dimensions`; I checked SpatialDeltaGLMM::Data_Fn() and t_i is a vector not a matrix.

**Comment by James-Thorson** [comment]
I recommend switching to VAST which is working with PlotIndex_Fn and includes all functionality from SpatialDeltaGLMM.  I'm update PlotIndex_Fn to backwards work with SpatialDeltaGLMM if anyone else +1s this issue.
