### ISSUE TITLE
 plot_residuals bugging in multispecies model

### ISSUE THREAD

**Issue by martin11112** [nwfsc-assess/geostatistical_delta-GLMM#46]
Hi, 
the function plot_residuals is bugging with my multispecies model (but it works with single-species models).
I get this error : Error in tapply(bpred_ipos[which_ipos_in_y], INDEX = factor(TmbData$s_i[which_i_in_y_and_pos],  : 
  arguments must have same length

Cheers 
Martin

**Comment by James-Thorson** [comment]
OK, please remove `SpatialDeltaGLMM` and re-install `VAST` and it should work.
