### ISSUE TITLE
Prepare_Extrapolation_Data_Fn function has disappeared

### ISSUE THREAD

**Issue by hmorzaria** [nwfsc-assess/geostatistical_delta-GLMM#48]
My code used 

Extrapolation_List <- SpatialDeltaGLMM::Prepare_Extrapolation_Data_Fn(Region=Region, strata.limits=strata.limits, observations_LL=Data_Geostat[,c('Lat','Lon')], maximum_distance_from_sample = maximum_distance_from_sample)
      
This worked 2 weeks ago, now I get 
ERROR : 'Prepare_Extrapolation_Data_Fn' is not an exported object from 'namespace:FishStatsUtils' 

The index for SpatialDeltaGLMM now shows the function Prepare_WCGBTS_Extrapolation_Data_Fn.

Do I just substitute directly Prepare_Extrapolation_Data_Fn for this new function?

**Comment by James-Thorson** [comment]
I apologize, I refactored the code base, and thought that I had done so in a way that was fully backwards compatible.  However, it clearly was not fully backwards compatible.

Please instead use:

`FishStatsUtils::make_extrapolation_info(Region=Region, strata.limits=strata.limits, observations_LL=Data_Geostat[,c('Lat','Lon')], maximum_distance_from_sample = maximum_distance_from_sample)`

and feel free to report back on this thread if you run into other issues.  There's a few name changes in basic functions (to meet ROpenSci naming conventions) and feel free to look at the Rmarkdown examples for the new names.

**Comment by hmorzaria** [comment]
Rmarkdown example SpatialDeltaGLMM_example.Rmd still uses Prepare_Extrapolation_Data_Fn and Spatial_Information_Fn; are there other new examples?

I also encountered the same issue with 
Spatial_Information_Fn (FishStatsUtils::make_spatial_info)

**Comment by James-Thorson** [comment]
I think I understand now -- you're using SpatialDeltaGLMM, which is now
deprecated. Are you willing to email arnaud and me for help to switch over
to VAST? If not I can help you install an older version of SpatialDeltaGLMM
from before the recent code refactoring, which will always be one form of
backwards compatibility

**Comment by hmorzaria** [comment]
Thanks, in general, I do want to switch over to VAST.
But for this project, I had completed all the models, and I just need go back and rerun two models again; for this reason, I would like to just install the older version of SpatialDeltaGLMM rather than redo all my code.

**Comment by James-Thorson** [comment]
OK, you can scroll through the list of commits here:
https://github.com/nwfsc-assess/geostatistical_delta-GLMM/commits/master

I think you can install everything you need using:

devtools::install_github( "nwfsc-assess/geostatistical_delta-GLMM",
ref="bff70484fb84ccafe72c4953679eafa0bfebd8d4" )

however, I haven't double checked.
