### ISSUE TITLE
Update README links to example models

### ISSUE THREAD

**Issue by taylori** [nwfsc-assess/geostatistical_delta-GLMM#7]
Looks like [https://github.com/nwfsc-assess/geostatistical_delta-GLMM/blob/master/examples/](https://github.com/nwfsc-assess/geostatistical_delta-GLMM/blob/master/examples/)
has been reconfigured so link to example_for_NWFSC_shelf-slope_data.R at bottom of README is broken. Not sure if it would be best to link to Example--simple.R or what.

**Comment by James-Thorson** [comment]
Yeah go ahead and switch the link, I gave up on maintaining two versions of the example

**Comment by taylori** [comment]
Fixed with recent commit: c309a8912920fe4982dc05c69fe79ffd2516486d
